In [6]:
SAMPLE_DIR = "/home/stavz/masters/gdc/APM/data/Methylation/raw_samples/Tumor/"
ANNOTATION_PATH = "/home/stavz/masters/gdc/APM/annotations/Methylation/probe_reference.tsv"

In [10]:
# annot = pd.read_csv(ANNOTATION_PATH, sep="\t")
sample = pd.read_csv(SAMPLE_DIR + "071a05c1-f9df-4e68-b73e-8f6716d75d52.methylation_array.sesame.level3betas.txt", sep="\t", header=None)

In [8]:
annot = pd.read_csv(ANNOTATION_PATH, sep="\t")

In [3]:
genes_cds = pd.read_csv(PATHS.genes_all_features)

In [17]:
lncrnas_cds = pd.read_csv(PATHS.lncrnas_all_features)

In [19]:
lncrnas_cds["feature"].value_counts()

feature
exon          26327
transcript     7929
gene           1635
Name: count, dtype: int64

In [ ]:
genes_cds["protein_coding"].value_counts()

transcript_type
protein_coding                    21696
nonsense_mediated_decay            3869
retained_intron                    1314
protein_coding_CDS_not_defined      573
Name: count, dtype: int64

In [1]:
import pandas as pd
import sys
sys.path.insert(0, '/home/stavz/masters/gdc/APM')
sys.path[0]
from pipeline.Methylation import run_methylation_pipeline
from pipeline.config import THRESHOLDS, PATHS

In [2]:
run_methylation_pipeline(include_tads=False)

======================================================================
METHYLATION PIPELINE
======================================================================

--------------------------------------------------
STEP 1: Building probe reference
--------------------------------------------------
======================================================================
BUILDING PROBE REFERENCE TABLE
======================================================================
Loading probe reference from \home\stavz\masters\gdc\APM\annotations\Methylation\probe_reference.tsv...
  Loaded 485577 probes
  Chromosomes: 26
  In CGI: 306516 (63.1%)
============================================================
ANNOTATING PROBE REFERENCE
============================================================
Annotating probes with gene promoters...
  Probes in promoters: 696 (0.14%)
Annotating probes with gene bodies...
  Probes in gene bodies: 1591 (0.33%)
Annotating probes with cCREs...
  Probes overlapping cCREs: 19878 (4.09%)
Annotating probes with lncRNA promoters...
  Probes in lncRNA promoters: 5882 (1.21%)
Annotating probes with ATAC peaks...
  Probes overlapping ATAC peaks: 26989 (5.56%)
============================================================
PROBE ANNOTATION COMPLETE
  Total probes: 485577
  In gene promoters: 696
  In gene bodies: 1591
  Overlapping cCREs: 19878
  In lncRNA promoters: 5882
  Overlapping ATAC: 26989
============================================================

======================================================================
PROBE REFERENCE COMPLETE
======================================================================

--------------------------------------------------
STEP 2: Processing individual samples
--------------------------------------------------

============================================================
Processing sample: TCGA-5L-AAT1-01A
============================================================
Processing sample: TCGA-5L-AAT1-01A
  Loaded 486427 probes
  Enriched with annotations
  Valid probes: 408464
  Mean beta: 0.486
******entered compute_sample_qc_metrics******
******exited compute_sample_qc_metrics******

QC Metrics:
  Valid probes: 408464 (84.0%)
  Mean beta: 0.486

Aggregating to gene level...
  Genes with promoter data: 59/66
Aggregating to lncRNA level...

\\wsl.localhost\Ubuntu\home/stavz/masters/gdc/APM\pipeline\Methylation\sample_processing.py:429: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cgi_mask = sample_df["in_CGI"].fillna(False).astype(bool)

no lncrna panel provided
Index(['lncrna_name', 'promoter_beta_mean', 'promoter_beta_median',
       'promoter_beta_std', 'promoter_beta_min', 'promoter_beta_max',
       'promoter_n_probes', 'promoter_beta_range', 'promoter_frac_hypermeth',
       'promoter_frac_hypometh', 'promoter_CGI_beta_mean',
       'promoter_CGI_n_probes', 'promoter_shore_beta_mean'],
      dtype='object')
  lncRNAs with promoter data: 859/486427
Aggregating to cCRE level...
  cCREs with data: 8369
saving lncRNA level...
saving lncRNA level...

Saved to: \home\stavz\masters\gdc\APM\data\Methylation\per_sample\TCGA-5L-AAT1-01A

============================================================
Processing sample: TCGA-AR-A2LR-01A
============================================================
Processing sample: TCGA-AR-A2LR-01A
  Loaded 486427 probes
  Enriched with annotations
  Valid probes: 417917
  Mean beta: 0.494
******entered compute_sample_qc_metrics******
******exited compute_sample_qc_metrics******

QC Metrics:
  Valid probes: 417917 (85.9%)
  Mean beta: 0.494

Aggregating to gene level...
  Genes with promoter data: 59/66
Aggregating to lncRNA level...

\\wsl.localhost\Ubuntu\home/stavz/masters/gdc/APM\pipeline\Methylation\sample_processing.py:429: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cgi_mask = sample_df["in_CGI"].fillna(False).astype(bool)

no lncrna panel provided
Index(['lncrna_name', 'promoter_beta_mean', 'promoter_beta_median',
       'promoter_beta_std', 'promoter_beta_min', 'promoter_beta_max',
       'promoter_n_probes', 'promoter_beta_range', 'promoter_frac_hypermeth',
       'promoter_frac_hypometh', 'promoter_CGI_beta_mean',
       'promoter_CGI_n_probes', 'promoter_shore_beta_mean'],
      dtype='object')
  lncRNAs with promoter data: 863/486427
Aggregating to cCRE level...
  cCREs with data: 8457
saving lncRNA level...
saving lncRNA level...

Saved to: \home\stavz\masters\gdc\APM\data\Methylation\per_sample\TCGA-AR-A2LR-01A
  Warning: File not found for TCGA-B6-A1KC-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ffc8fa8f-f6f7-4b8a-9773-b29dc0a60410.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AQ-A0Y5-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\27fe0b6c-1b76-400b-a0ef-9405f833c482.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AO-A1KQ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\a3faa9fb-cbea-4ae5-8bf4-ca9b9f04a55f.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A1XU-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\fa1b44dd-3960-4ce1-be3c-2e2e0e7ece66.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A1-A0SN-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\88c8a133-1c35-4e23-88d3-042cbca01208.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0W5-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\bbf9988a-7181-4388-b39d-c4327051fed9.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AO-A124-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\20171ef3-0986-476f-96f8-9d6051835771.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A7-A6VV-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\4f6114a2-0125-4bf5-8d62-d890fa751ee9.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0BZ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ea91d00f-af87-49b8-b7ee-0fb7f486c904.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1FE-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c9c7106d-96eb-4f60-b0bf-b2b6395d7f7b.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1FE-06A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6366b160-c124-4a56-b6a7-e159ea8a096d.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A3XX-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\d313dc0e-3840-487d-be90-817a1ef43f82.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0B2-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6efbf774-e5f0-45e2-aa14-554c0604bb02.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-EW-A1PC-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8363a413-fc96-4dbb-b460-00577fbfefae.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A3XW-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\2cfc41ee-6c94-43a1-b234-14d2e96f6db3.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1FB-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\a1d39cbf-1713-45c7-a4e8-665c8d148f21.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A5J0-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c9ec30b8-f7c0-4279-ab7a-16ee41de0d57.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1B1-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\a1f11587-5a03-4d47-8588-ca849d981ace.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A0WX-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\78813fe8-7c09-476a-bc5a-4796f9ac76f2.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A255-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\804b4dc5-5734-4cee-ac9f-cf96f89a7740.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A0U3-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\891a7d85-d1c6-486b-ae5c-393f3c7ef5b7.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-UL-AAZ6-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\5acb3c47-eb9c-4cdb-89dc-4891d4f57fd6.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1F8-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\bf2fd308-86da-443c-886b-a68fb127cea7.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A3HN-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\0281de9b-0aed-44bd-b4bc-a2636826f92a.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A108-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\82bbcff8-dcc2-4e2e-88cb-65972d65a30c.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A0RT-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\590ef5f8-15bf-4aef-b5ad-e7d8951f7281.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1IN-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\03b9eb14-2540-4ccf-8aee-3f34a87f24e8.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A1FW-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\179f5c2e-5b74-428e-913f-f974ea580e27.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A7-A26G-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ee0e3cc4-e027-4a62-a5cf-e9a5c67e086d.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1IJ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8ebc5412-c2b7-4fd7-852c-fca4cf48cadf.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A1HK-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6f47fe3d-d42a-472b-b69a-6e4c20b69893.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-3C-AALK-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\a5ac8fac-e653-4767-8629-82a8bdccc0b7.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A2FK-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\1b79fa1c-4c59-4bc8-8e77-90a700d73be8.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-GM-A2DK-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\66d3cdf0-3bdb-4fa2-b3cf-07d0603ff252.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1F6-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\34340955-ae0e-4c75-bf01-4e8f42251c04.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-XX-A89A-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\2b34151a-9892-4e15-bcc1-af9829075e49.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E9-A5UO-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\50c873e3-b33f-4f8e-9101-2da96601a3d2.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1LB-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\0247ae5b-2c4b-4190-aa02-ccec21933db3.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A15I-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ebc5fba5-4d76-4c73-8e6a-a2543f2dd210.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-EW-A6SB-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c728239c-fca8-4c7d-93ac-0f4738153a3f.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-EW-A3E8-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8fd5c0fe-6755-42c1-8f54-a554b09d9a43.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1ES-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\7398681f-04ae-4777-bd98-5ce49bc89bb0.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-OL-A97C-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\23523a69-8bfd-4108-ba0a-762a68e1cf68.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A26X-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ba80f67f-04f5-47d1-b921-fec7d83295e9.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A1XA-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\578d5d21-544b-42c3-97d7-e0a1838d1437.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1B5-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8d798bd9-8095-4311-81aa-b6d02fe467b7.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A9FZ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f1714837-e2d2-4ef8-a2e6-01c043f91561.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A6IX-06A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\829e623e-d13b-41f9-9421-3774c54234f1.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A1B0-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6eaeaa1d-eb70-4ad1-8f3a-129f83ba1210.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A14N-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c430c2bc-2277-4227-a2b6-667099f2e619.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A10C-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\4028f62d-550a-49b3-869a-355f1f6c6cca.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A0RG-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\9803ac9c-d4a6-42ed-8e31-7a7b813030f8.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E9-A24A-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\3bacf66d-0a60-438a-811c-0163cc508d7e.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-PL-A8LY-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\163799b6-69de-48d8-87f6-59952ffbe9c0.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A27E-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c650bc79-8d29-4c3e-9ec6-6fbc7aba838a.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A7-A26J-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\06070786-4f18-4ebd-afdc-837af04198b5.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A7-A26J-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8f009c0c-5f4a-453e-8f09-5576a11c2462.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A8HQ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\edd37da2-cdb9-4476-847b-61b1f2d6e166.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A3TM-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f1fd6980-0dce-47ea-893d-47c65502a2c7.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A7-A0DC-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\727d2856-09cb-4131-9052-f3cd85136cef.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-LL-A6FP-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\d9a51484-0d7f-423c-a3b2-93df9ce5da76.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A1HO-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\29644452-cc56-4895-a959-c7a1c344444a.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A1KC-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\9bc2055b-86f4-4ab7-80db-568b8d65b9f3.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A1HI-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f7e81ca6-5c0e-4fc1-bdcf-9ddc0749fd01.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AO-A0JI-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\cb3b3878-adfb-41e0-9f1a-971f38df16dd.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0C0-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\435578b0-5e1b-4c59-bc82-5020c98775c2.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A2QH-01B: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f2a6ab54-ed90-483c-9258-2ed63537bbd1.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AN-A0XW-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\50ab9ba6-b3c8-460d-818a-a8b5c20ddf3b.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A8OP-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\82978eff-30b4-48a0-8806-78d3d8f7ad70.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-LL-A442-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\d1ed45d1-f095-4a81-a71a-9326f5cd1b36.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A1XR-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\2df1fa7b-f792-4d16-aa95-b0ed80222b9b.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A0SV-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\147ce471-adc9-4579-8088-c3f370bcbec0.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-3C-AAAU-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c9898911-dbb4-4e99-b6ea-a7a2411fbd4a.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A1XB-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\3937670b-62c1-4b7c-b32f-69f9d5c673e1.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A1FD-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f9fe6e9e-a4ab-47b3-8af3-f851d0303a3e.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A0X5-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6314d1f5-21d4-4268-ae22-93eec57cd6d5.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A0EP-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\5e343950-561c-411c-8c2a-68606c32e5a4.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0BS-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\d0494cac-36fe-4668-9b79-83a748392539.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E2-A572-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\228e17a9-9761-4dd2-9e99-775da7045ff1.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0DI-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\e633d9e7-3a6b-490a-b464-d5f74478d90d.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A0TW-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\4f9415dd-e520-45f1-a659-55cb6554fc71.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-B6-A0RM-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8ad13ac2-cb63-4a69-8229-e5bef8411afe.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E9-A5UP-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\f54eb7f3-c9db-4ea3-bd32-225e3b863a7d.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-E9-A1QZ-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\9573bb8e-3f1c-42e4-b3b2-aeaa778182c4.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-C8-A278-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\3fd77df6-2b96-4c53-b14d-9a4036f8608f.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AC-A23E-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\c7e263f9-aa7a-47af-8522-b1dccdabffc0.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A6R8-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\fd6f04e1-8cc7-41c9-a9a1-9e46e780fb99.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-LD-A9QF-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8b745c0c-58c3-4c25-8c20-084242c9569c.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0H0-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ed2a8602-3dd1-4393-b9dd-d42636da4d71.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-EW-A1PH-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\bc666b44-589d-42be-8d26-ac0ee82b9705.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0H9-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\3962ba19-7e59-435c-b0ca-fc5fa9262717.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A0U2-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\36ce30a5-778c-48bb-bd89-039d1830400d.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A1AS-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\0d68f961-141e-44cc-8f1a-cddd16d3fae1.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A27K-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\169909e8-467b-45e3-8b30-f24ebbad7e3a.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0DP-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\d2b4e92f-5c77-4bc8-bd39-f565160c9fea.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-W8-A86G-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\6072b31c-e577-453f-8289-99eb2efd01a3.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-D8-A1XC-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\802ef530-9a93-4e08-89ad-7b629744b080.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-BH-A0B5-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\8acb1cfe-94a5-4c37-be0c-5a124129a8ba.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A3KD-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\5b2393d4-f559-4253-8942-65f6b7af087c.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-EW-A1P8-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\97746d64-3ec5-47a7-b029-29608a77f9a4.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-A2-A4S2-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\ceb1e65a-a14d-4177-aadd-6fbf0b9155c0.methylation_array.sesame.level3betas.txt
  Warning: File not found for TCGA-AR-A0U0-01A: \home\stavz\masters\gdc\APM\data\Methylation\raw_samples\Tumor\a7fd4ada-7db5-4418-a80f-4142323d8915.methylation_array.sesame.level3betas.txt

\\wsl.localhost\Ubuntu\home/stavz/masters/gdc/APM\pipeline\Methylation\sample_processing.py:429: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cgi_mask = sample_df["in_CGI"].fillna(False).astype(bool)

no lncrna panel provided
Index(['lncrna_name', 'promoter_beta_mean', 'promoter_beta_median',
       'promoter_beta_std', 'promoter_beta_min', 'promoter_beta_max',
       'promoter_n_probes', 'promoter_beta_range', 'promoter_frac_hypermeth',
       'promoter_frac_hypometh', 'promoter_CGI_beta_mean',
       'promoter_CGI_n_probes', 'promoter_shore_beta_mean'],
      dtype='object')

[2/2] Processing TCGA-AR-A2LR-01A...
******entered compute_sample_qc_metrics******
******exited compute_sample_qc_metrics******

\\wsl.localhost\Ubuntu\home/stavz/masters/gdc/APM\pipeline\Methylation\sample_processing.py:429: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cgi_mask = sample_df["in_CGI"].fillna(False).astype(bool)

no lncrna panel provided
Index(['lncrna_name', 'promoter_beta_mean', 'promoter_beta_median',
       'promoter_beta_std', 'promoter_beta_min', 'promoter_beta_max',
       'promoter_n_probes', 'promoter_beta_range', 'promoter_frac_hypermeth',
       'promoter_frac_hypometh', 'promoter_CGI_beta_mean',
       'promoter_CGI_n_probes', 'promoter_shore_beta_mean'],
      dtype='object')

Gene matrix (+meta): (66, 3)
lncRNA matrix (+meta): (863, 3)
cCRE matrix (+meta): (8480, 3)
ATAC matrix (+meta): (9478, 3)

Saved cohort matrices to: \home\stavz\masters\gdc\APM\data\Methylation\cohort

======================================================================
METHYLATION PIPELINE COMPLETE
======================================================================
Working directory: \home\stavz\masters\gdc\APM\data\Methylation

{'working_dir': '\\home\\stavz\\masters\\gdc\\APM\\data\\Methylation',
 'probe_reference_path': '\\home\\stavz\\masters\\gdc\\APM\\data\\Methylation\\reference\\probe_annotations.parquet',
 'per_sample_dir': '\\home\\stavz\\masters\\gdc\\APM\\data\\Methylation\\per_sample',
 'cohort_dir': '\\home\\stavz\\masters\\gdc\\APM\\data\\Methylation\\cohort',
 'cohort_stats': {'n_samples': 2,
  'gene_matrix_shape': [66, 3],
  'ccre_matrix_shape': [8480, 3]}}

In [8]:
import sys, pandas as pd
print(sys.executable)
print(pd.__version__)

c:\Users\stavz\AppData\Local\Programs\Python\Python311\python.exe
2.3.3

In [3]:
peak_ids = pd.read_csv(PATHS.atac_peaks_mapping_csv)

In [4]:
peak_ids

                      peak_id original_name chrom     start       end
0      chr1:63042199-63042700     UCEC_3838  chr1  63042199  63042700
1      chr1:63051325-63051826     KIRC_3640  chr1  63051325  63051826
2      chr1:63051840-63052341     KIRC_3641  chr1  63051840  63052341
3      chr1:63087923-63088424      GBM_2589  chr1  63087923  63088424
4      chr1:63099114-63099615     SKCM_3569  chr1  63099114  63099615
...                       ...           ...   ...       ...       ...
44795    chr9:7523596-7524097    LUAD_71053  chr9   7523596   7524097
44796    chr9:7536303-7536804    COAD_60191  chr9   7536303   7536804
44797    chr9:7542712-7543213     GBM_39797  chr9   7542712   7543213
44798    chr9:7543413-7543914    BLCA_51253  chr9   7543413   7543914
44799    chr9:7549159-7549660    THCA_45568  chr9   7549159   7549660

[44800 rows x 5 columns]

In [3]:
rppa = pd.read_csv("/home/stavz/masters/gdc/APM/annotations/RPPA/TCGA_antibodies_descriptions.gencode.v36.tsv", sep="\t")

In [13]:
rppa

,AGID,peptide_target,gene_name,antibody_origin,source,catalog_number,validation_status,gene_id
0,AGID00100,1433BETA,YWHAB,Rabbit,Santa Cruz,sc-628,Valid,ENSG00000166913.13
1,AGID00111,1433EPSILON,YWHAE,Mouse,Santa Cruz,sc-23957,Caution,ENSG00000108953.17
2,AGID00101,1433ZETA,YWHAZ,Rabbit,Santa Cruz,sc-1019,Valid,ENSG00000164924.18
3,AGID00001,4EBP1,EIF4EBP1,Rabbit,CST,9452,Valid,ENSG00000187840.5
4,AGID00002,4EBP1_pS65,EIF4EBP1,Rabbit,CST,9456,Valid,ENSG00000187840.5
...,...,...,...,...,...,...,...,...
482,AGID00095,YB1_pS102,YBX1,Rabbit,CST,2900,Valid,ENSG00000065978.19
483,AGID02217,YTHDF2,YTHDF2,Rabbit,Abcam,ab220163,Valid,ENSG00000198492.16
484,AGID02210,YTHDF3,YTHDF3,Rabbit,Abcam,ab220161,Caution,ENSG00000185728.17
485,AGID00326,ZAP-70,ZAP70,Rabbit,CST,2705,Valid,ENSG00000115085.14
486,AGID00432,ZEB1,ZEB1,Rabbit,Santa Cruz,sc-25388,Valid,ENSG00000148516.22

In [7]:
rppa["validation_status"].value_counts()

validation_status
Valid               283
Caution             197
Under Evaluation      7
Name: count, dtype: int64

In [12]:
rppa

,AGID,peptide_target,gene_name,antibody_origin,source,catalog_number,validation_status,gene_id
0,AGID00100,1433BETA,YWHAB,Rabbit,Santa Cruz,sc-628,Valid,ENSG00000166913.13
1,AGID00111,1433EPSILON,YWHAE,Mouse,Santa Cruz,sc-23957,Caution,ENSG00000108953.17
2,AGID00101,1433ZETA,YWHAZ,Rabbit,Santa Cruz,sc-1019,Valid,ENSG00000164924.18
3,AGID00001,4EBP1,EIF4EBP1,Rabbit,CST,9452,Valid,ENSG00000187840.5
4,AGID00002,4EBP1_pS65,EIF4EBP1,Rabbit,CST,9456,Valid,ENSG00000187840.5
...,...,...,...,...,...,...,...,...
482,AGID00095,YB1_pS102,YBX1,Rabbit,CST,2900,Valid,ENSG00000065978.19
483,AGID02217,YTHDF2,YTHDF2,Rabbit,Abcam,ab220163,Valid,ENSG00000198492.16
484,AGID02210,YTHDF3,YTHDF3,Rabbit,Abcam,ab220161,Caution,ENSG00000185728.17
485,AGID00326,ZAP-70,ZAP70,Rabbit,CST,2705,Valid,ENSG00000115085.14
486,AGID00432,ZEB1,ZEB1,Rabbit,Santa Cruz,sc-25388,Valid,ENSG00000148516.22