In [2]:
import pandas as pd
# xcell = pd.read_csv(r"\home\stavz\masters\gdc\APM\data\RNAexp_TCGA\xcell_results\xCell_BRCA_log2_expression_xCell_1300020226.txt", sep="\t", index_col=0)

In [3]:
brca_clin = pd.read_csv(r"\home\stavz\masters\gdc\APM\annotations\BRCA_clinical", sep="\t", index_col=0)

In [26]:
import sys
sys.path.insert(0, r"/home/stavz/masters/gdc/APM")
from pipeline.config import PATHS
PAM50 = pd.read_csv(PATHS.immune_subtype_annotations, sep="\t", index_col=0)
brca_clin = pd.read_csv(r"\home\stavz\masters\gdc\APM\annotations\BRCA_immune_subtypes.tsv", sep="\t")

In [35]:
PAM50

,PAM50_recomputed,PAM50Call_RNAseq,PAM50_final,thornsson_subtype
sample_id,,,,
TCGA-3C-AAAU-01,LumB,NaN,LumB,NaN
TCGA-3C-AALI-01,Her2,NaN,Her2,NaN
TCGA-3C-AALJ-01,LumB,NaN,LumB,NaN
TCGA-3C-AALK-01,LumA,NaN,LumA,NaN
TCGA-4H-AAAK-01,LumA,NaN,LumA,NaN
...,...,...,...,...
TCGA-WT-AB44-01,LumA,NaN,LumA,NaN
TCGA-XX-A899-01,LumA,NaN,LumA,NaN
TCGA-XX-A89A-01,LumA,NaN,LumA,NaN
TCGA-Z7-A8R5-01,Normal,NaN,Normal,NaN
TCGA-Z7-A8R6-01,LumB,NaN,LumB,NaN

In [37]:
purity = pd.read_excel(
    r"/home/stavz/masters/gdc/APM/data/RNAexp_TCGA/Purity_2015.xlsx", header = 3
    
)

c:\Users\stavz\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [38]:
purity["suffix"] = purity["Sample ID"].str.split("-").str[-1]
purity

,Sample ID,Cancer type,ESTIMATE,ABSOLUTE,LUMP,IHC,CPE,Unnamed: 7,suffix
0,TCGA-OR-A5J1-01A,ACC,0.9368,NaN,0.9774,0.80,0.9246,NaN,01A
1,TCGA-OR-A5J2-01A,ACC,0.9175,NaN,0.6174,0.95,0.8985,NaN,01A
2,TCGA-OR-A5J3-01A,ACC,0.9670,NaN,0.9249,0.80,0.9466,NaN,01A
3,TCGA-OR-A5J4-01A,ACC,NaN,NaN,0.9199,0.80,0.8660,NaN,01A
4,TCGA-OR-A5J5-01A,ACC,0.9761,NaN,1.0000,0.80,0.9780,NaN,01A
...,...,...,...,...,...,...,...,...,...
9359,TCGA-NF-A5CP-01A,UCS,0.7410,NaN,0.7424,0.90,0.7320,NaN,01A
9360,TCGA-NG-A4VU-01A,UCS,0.9032,NaN,0.8593,0.90,0.8695,NaN,01A
9361,TCGA-NG-A4VW-01A,UCS,0.9792,NaN,0.4124,0.95,0.7913,NaN,01A
9362,TCGA-QM-A5NM-01A,UCS,0.9630,NaN,0.9832,1.00,0.9602,NaN,01A
9363,TCGA-QN-A5NN-01A,UCS,0.8070,NaN,0.7592,0.90,0.7518,NaN,01A

In [51]:
rna = pd.read_csv(r"\home\stavz\masters\gdc\APM\data\RNAexp_TCGA\BRCA_log2_expression.tsv", sep="\t", index_col=0)

In [39]:
brca = purity[purity["Cancer type"] == "BRCA"]

In [52]:
rna

,TCGA-AR-A5QQ-01,TCGA-D8-A1JA-01,TCGA-BH-A0BQ-01,TCGA-BH-A0BT-01,TCGA-A8-A06X-01,TCGA-A8-A096-01,TCGA-BH-A0C7-01,TCGA-AC-A5XU-01,TCGA-PE-A5DE-01,TCGA-PE-A5DC-01,...,TCGA-A7-A13E-11,TCGA-C8-A8HP-01,TCGA-E9-A5FL-01,TCGA-AC-A2FB-11,TCGA-E2-A15F-01,TCGA-A2-A3XT-01,TCGA-B6-A0X7-01,TCGA-BH-A1EV-11,TCGA-3C-AALJ-01,TCGA-B6-A0X1-01
sample,,,,,,,,,,,,,,,,,,,,,
ARHGEF10L,9.5074,7.4346,9.3216,9.0198,9.6417,9.7665,10.0931,9.1524,9.9398,9.6287,...,9.6265,10.1826,9.9199,9.9090,10.0334,11.5144,10.5745,9.4048,10.9468,10.3164
HIF3A,1.5787,3.6607,2.7224,1.3414,0.5819,0.2738,3.6090,0.4738,2.9378,4.1136,...,8.1546,2.2159,3.8645,8.1872,0.8836,1.3169,4.0696,7.2537,0.9310,2.4191
RNF17,0.0000,0.6245,0.5526,0.0000,0.0000,0.8765,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,3.7305,0.0000,0.0000,1.1329,0.4258,0.0000,0.0000,0.0000
RNF10,11.3676,11.9181,11.9665,13.1881,12.0036,11.8118,11.3820,11.5004,12.2055,12.1312,...,11.9869,12.2653,12.4815,11.8263,12.0135,11.5818,11.8663,11.5460,12.2616,12.1570
RNF11,11.1292,13.5273,11.4105,11.0911,11.2545,10.8554,10.7663,10.4358,11.2210,10.8013,...,11.9344,11.4117,10.4902,11.5754,10.8370,10.2736,10.7644,11.8774,10.7842,11.2420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PTRF,13.8808,10.7066,12.9973,12.3298,11.3338,12.7711,11.8181,12.8073,12.1288,12.3841,...,14.3703,12.2506,12.9838,14.5242,11.3156,11.2605,12.7548,13.1131,12.5534,9.5126
BCL6B,7.3830,7.2467,8.3374,7.7036,7.7186,8.7307,7.9077,8.9854,8.3610,8.9031,...,9.7785,7.5557,7.9937,9.1906,7.7383,8.4863,9.0657,8.7063,8.7597,6.1074
GSTK1,11.4289,9.1673,11.3400,11.3025,10.6898,10.5158,10.7539,11.4017,11.4528,11.6460,...,11.6932,11.4918,11.1088,11.4123,10.7775,10.9538,11.1277,10.9711,12.0469,11.5929
SELP,7.8456,0.0000,8.3765,7.0585,7.0992,5.9003,6.5823,4.1152,8.8560,8.2783,...,9.9759,7.2450,4.6751,9.7228,8.1673,5.6838,8.6348,9.4892,5.6941,1.6664
SELS,10.7384,10.1225,9.9367,9.3784,11.1740,9.8729,9.7063,10.2758,10.0925,10.7905,...,9.6608,10.1750,10.1457,9.8622,10.2218,10.8272,9.6448,9.6596,10.1682,9.3894

In [ ]:
import re
import numpy as np

# key for PAM50 index: "TCGA-3C-AAAU-01"
PAM50_key = PAM50.index.to_series().str.extract(r'^(TCGA-[^-]+-[^-]+-\d\d)')[0]

# key + aliquot for brca "Sample ID": "TCGA-3C-AAAU-01A" -> key="...-01", aliquot="A"
brca_tmp = brca[["Sample ID", "CPE"]].copy()
brca_tmp["key"] = brca_tmp["Sample ID"].str.extract(r'^(TCGA-[^-]+-[^-]+-\d\d)')[0]
brca_tmp["aliquot"] = brca_tmp["Sample ID"].str.extract(r'^TCGA-[^-]+-[^-]+-\d\d([A-Z])')[0]

# priority order
order = {"A": 0, "B": 1, "C": 2}
brca_tmp["aliquot_rank"] = brca_tmp["aliquot"].map(order).fillna(99)

# pick best-ranked aliquot per key
brca_best = (
    brca_tmp.sort_values(["key", "aliquot_rank"])
            .drop_duplicates("key", keep="first")
            .set_index("key")["CPE"]
)

# map into PAM50
PAM50["CPE"] = PAM50_key.map(brca_best).to_numpy()

In [49]:
PAM50.to_csv(PATHS.immune_subtype_annotations, sep="\t", index=False)

In [37]:
rna_other = pd.read_csv(r"\home\stavz\masters\gdc\APM\data\RNAexp_TCGA\tcga_RSEM_gene_tpm", sep="\t", index_col=0)

In [52]:
idmap = pd.read_csv(r"\home\stavz\masters\gdc\APM\data\RNAexp_TCGA\id_map_tpm.probemap", sep="\t", index_col=0)

In [53]:
idmap

                           gene chrom  chromStart  chromEnd strand
id
ENSG00000223972.5       DDX11L1  chr1       11869     14409      +
ENSG00000227232.5        WASH7P  chr1       14404     29570      -
ENSG00000278267.1     MIR6859-1  chr1       17369     17436      -
ENSG00000243485.3  RP11-34P13.3  chr1       29554     31109      +
ENSG00000274890.1     MIR1302-2  chr1       30366     30503      +
...                         ...   ...         ...       ...    ...
ENSG00000198695.2        MT-ND6  chrM       14149     14673      -
ENSG00000210194.1         MT-TE  chrM       14674     14742      -
ENSG00000198727.2        MT-CYB  chrM       14747     15887      +
ENSG00000210195.2         MT-TT  chrM       15888     15953      +
ENSG00000210196.2         MT-TP  chrM       15956     16023      -

[60498 rows x 5 columns]

In [54]:
brca_cols = [c for c in rna_other.columns if c in brca_clin.index]
brca_rna = rna_other[brca_cols]
brca_rna = rna_other.join(idmap, how="left")

In [56]:
brca_rna.reset_index().set_index("gene")

,sample,TCGA-19-1787-01,TCGA-S9-A7J2-01,TCGA-G3-A3CH-11,TCGA-EK-A2RE-01,TCGA-44-6778-01,TCGA-F4-6854-01,TCGA-AB-2863-03,TCGA-C8-A1HL-01,TCGA-EW-A2FS-01,...,TCGA-95-7947-01,TCGA-VQ-AA6F-01,TCGA-BR-8588-01,TCGA-24-2254-01,TCGA-DD-A115-01,TCGA-FV-A3I0-11,chrom,chromStart,chromEnd,strand
gene,,,,,,,,,,,,,,,,,,,,,
RP11-368I23.2,ENSG00000242268.2,-9.9658,0.2998,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-1.9379,-9.9658,-9.9658,chr3,168903366,168921996,+
RP11-167B3.1,ENSG00000259041.1,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,chr15,98282075,98285907,+
RP11-742D12.2,ENSG00000270112.3,-3.8160,-3.0469,-9.9658,-9.9658,-5.5735,-9.9658,-3.4580,-9.9658,-5.0116,...,-6.5064,-9.9658,-9.9658,-5.5735,-9.9658,-9.9658,chr18,46756487,46764408,+
RAB4B,ENSG00000167578.16,5.2998,4.8881,3.5572,4.2563,5.3162,4.5161,3.6242,4.9782,5.7035,...,6.1607,5.2814,3.9599,5.0760,4.0260,3.0876,chr19,40778216,40796944,+
AC104071.1,ENSG00000278814.1,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,chr4,31349786,31349874,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RP11-713D19.1,ENSG00000273233.1,-1.2481,-1.2142,-9.9658,-1.8836,-9.9658,-9.9658,-9.9658,-9.9658,-0.9686,...,-2.4659,-4.2934,-2.5479,-1.8836,-9.9658,-9.9658,chr2,28810281,28810706,-
PPP6R1,ENSG00000105063.18,5.2661,4.8151,3.4358,5.2851,5.6436,5.5958,6.7544,4.4095,4.4081,...,6.0228,6.1252,5.1473,6.2593,4.4647,3.2174,chr19,55229780,55258995,-
RP4-569M23.2,ENSG00000231119.2,-0.2159,-3.3076,-2.5479,-5.0116,-1.3548,-9.9658,-0.9132,-5.0116,-1.8836,...,-1.7322,-1.6850,-3.6259,-0.5543,-2.3884,-3.0469,chr20,47352561,47354633,+
AC009260.1,ENSG00000280861.1,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,chr12,114340790,114340908,+
OR8D4,ENSG00000181518.3,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-5.0116,-9.9658,-9.9658,chr11,123906146,123907476,+

In [56]:
GENES_PATH = r"\home\stavz\masters\gdc\APM\data\primary_genes_all_features.csv"
genes = pd.read_csv(GENES_PATH)

In [59]:
genes["tag"].value_counts()

tag
CCDS                         9727
TAGENE                       6294
RNA_Seq_supported_only       2298
appris_alternative_1         1608
basic                        1510
appris_alternative_2          787
cds_start_NF                  690
GENCODE_Primary               663
cds_end_NF                    433
exp_conf                      291
NAGNAG_splice_site            208
RNA_Seq_supported_partial     165
alternative_5_UTR              93
not_organism_supported         91
inferred_transcript_model      60
NMD_likely_if_extended         56
alternative_3_UTR              53
mRNA_end_NF                    32
appris_principal_4             31
upstream_uORF                  27
non_canonical_other            21
CAGE_supported_TSS             13
dotter_confirmed               13
overlapping_locus              12
non_canonical_TEC              11
ncRNA_host                      7
Name: count, dtype: int64