In [3]:
import pandas as pd
cl = pd.read_csv("annotations/BRCA_clinical", sep="\t")

In [ ]:
recomp = pd.read_csv(r"\\wsl.localhost\Ubuntu\home\stavz\masters\gdc\RNAexp\BRCA_PAM50_merged.tsv", sep="\t")
recomp["PAM50_final"] = recomp["PAM50Call_RNAseq"].fillna(recomp["PAM50_recomputed"])
immune_subtypes = pd.read_excel(r"annotations/BRCA_immune_subtypes.xlsx")
immune_subtypes[immune_subtypes["TCGA Study"] == "BRCA"].to_csv(r"annotations/BRCA_immune_subtypes.tsv", index=False, sep="\t")
immune_subtypes.to_csv(r"annotations/TCGA_immune_subtypes.tsv", index=False, sep="\t")

In [ ]:
immune_subtypes_BRCA = pd.read_csv(r"annotations/BRCA_immune_subtypes.tsv", sep="\t")
tmp = cl["sampleID"].str.split("-", expand=True)
cl_tumor = cl[tmp[3] == "01"]   # usually "01A", sometimes just "01"

tmp = recomp["sample_id"].str.split("-", expand=True)
recomp_tumor = recomp[tmp[3] == "01"]   # usually "01A", sometimes just "01"
recomp_tumor["sample_id_short"] = recomp_tumor["sample_id"].str[:-3]

In [202]:
cl["PAM50Call_RNAseq"].value_counts().sum()

np.int64(956)

In [244]:
immune_subtypes

,TCGA Participant Barcode,TCGA Study,Immune Subtype,TCGA Subtype,Leukocyte Fraction,Stromal Fraction,Intratumor Heterogeneity,TIL Regional Fraction,Proliferation,Wound Healing,...,T Cells CD8,T Cells Follicular Helper,T Cells gamma delta,T Cells Regulatory Tregs,Lymphocytes,Neutrophils.1,Eosinophils.1,Mast Cells,Dendritic Cells,Macrophages
0,TCGA-01-0639,OV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCGA-02-0007,GBM,NaN,GBM_LGG.Classic-like,0.047660,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TCGA-02-0011,GBM,NaN,GBM_LGG.LGm6-GBM,0.062099,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TCGA-02-0023,GBM,NaN,GBM_LGG.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TCGA-02-0025,GBM,NaN,GBM_LGG.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11075,TCGA-ZJ-AAXJ,CESC,C2,NaN,0.190520,0.28,0.06,3.508290,1.0591,0.4380,...,0.109746,0.158487,0.053922,0.025416,0.588338,0.001046,0.0,0.016717,0.218868,0.175031
11076,TCGA-ZJ-AB0I,CESC,C2,NaN,0.059910,0.10,0.03,2.915626,0.9968,0.3120,...,0.227673,0.082950,0.000000,0.050475,0.475620,0.001589,0.0,0.082539,0.028535,0.411717
11077,TCGA-ZN-A9VU,MESO,C2,NaN,0.272642,0.39,0.01,NaN,-0.4574,-0.1410,...,0.074590,0.049620,0.000000,0.000000,0.470148,0.000000,0.0,0.123572,0.027675,0.378605
11078,TCGA-ZN-A9VW,MESO,C6,NaN,0.286224,0.35,0.01,NaN,0.4057,0.0475,...,0.236810,0.076568,0.000000,0.046645,0.426932,0.000000,0.0,0.002948,0.003850,0.566270
11079,TCGA-ZX-AA5X,CESC,C2,NaN,0.365432,0.63,0.05,6.331015,0.4389,0.1040,...,0.063557,0.030103,0.000000,0.035398,0.500590,0.013510,0.0,0.089936,0.054174,0.341790

In [243]:
recomp_tumor["PAM50_final"].value_counts()

PAM50_final
LumA      507
LumB      264
Basal     197
Her2       93
Normal     36
Name: count, dtype: int64

In [232]:
cl = cl.merge(recomp_tumor[["sample_short", "PAM50_final"]], left_on="sampleID", right_on="sample_short", how="left")
cl.drop(columns=["sample_short"], inplace=True)

In [240]:
immune_subtypes_BRCA

,TCGA Participant Barcode,TCGA Study,Immune Subtype,TCGA Subtype,pathologic_stage,pathologic_T,pathologic_N,pathologic_M,PAM50_final,PAM50Call_RNAseq,...,T Cells gamma delta,TCR Evenness,TCR Richness,TCR Shannon,TGF-beta Response,TIL Regional Fraction,Th1 Cells,Th17 Cells,Th2 Cells,Wound Healing
0,TCGA-4H-AAAK,BRCA,C1,BRCA.LumA,Stage IIIA,T2,N2a,M0,LumA,NaN,...,0.0,0.989151,19.0,2.912494,0.7173,0.229580,-633.296078,777.948283,48.873581,-0.0490
1,TCGA-A1-A0SM,BRCA,C1,BRCA.LumA,Stage IIA,T2,N0 (i-),M0,LumA,LumA,...,0.0,NaN,1.0,0.000000,0.6972,2.264620,-407.748977,3328.837789,919.895731,-0.0325
2,TCGA-A2-A0CO,BRCA,C2,BRCA.LumA,Stage IIB,T3,N0,M0,LumA,NaN,...,0.0,0.975294,44.0,3.690696,0.4972,0.253570,380.358214,2325.114728,-332.434256,-0.2790
3,TCGA-A2-A0CQ,BRCA,C4,BRCA.LumA,Stage IA,T1,N0 (i-),M0,LumA,LumA,...,0.0,1.000000,12.0,2.484907,0.0635,1.317346,-1159.985350,1335.395101,553.020419,-0.0625
4,TCGA-A2-A0EU,BRCA,C1,BRCA.LumA,Stage IA,T1c,N0 (i-),M0,LumA,LumA,...,0.0,0.968393,6.0,1.735126,0.2129,1.295632,-750.462620,-2379.686581,592.676210,0.0595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,TCGA-PE-A5DD,BRCA,C1,BRCA.LumA,Stage IIA,T2,N0,M0,LumB,NaN,...,0.0,0.950918,17.0,2.694154,0.4787,0.650684,-1105.513005,872.489833,-298.941787,-0.0740
1083,TCGA-PL-A8LV,BRCA,C1,BRCA.Basal,Stage IIIB,T4,N0,M0,Basal,NaN,...,0.0,0.994172,33.0,3.476131,0.1897,NaN,-1069.900069,-125.497439,248.551054,0.1340
1084,TCGA-S3-AA14,BRCA,C1,BRCA.LumA,Stage I,T1,N0 (i+),cM0 (i+),Her2,NaN,...,0.0,1.000000,8.0,2.079442,0.5820,NaN,-793.169515,986.138159,469.916751,-0.0525
1085,TCGA-WT-AB41,BRCA,C2,BRCA.LumA,Stage IIB,T2,N1mi,MX,LumB,NaN,...,0.0,0.975373,35.0,3.467791,0.0073,3.437699,20.921374,622.796168,-461.010812,-0.0075
1086,TCGA-Z7-A8R5,BRCA,C1,BRCA.LumA,Stage IIIA,T3,N1a,MX,Normal,NaN,...,0.0,0.985993,15.0,2.670120,0.2821,NaN,-570.839006,2169.373670,-628.006681,-0.0030

In [196]:
immune_subtypes_BRCA =immune_subtypes_BRCA.merge(cl_tumor[["sampleID_short", "pathologic_stage","pathologic_T", "pathologic_N", "pathologic_M", "ER_Status_nature2012", "PR_Status_nature2012", "HER2_Final_Status_nature2012"]], left_on="TCGA Participant Barcode", right_on="sampleID_short", how="left")
immune_subtypes_BRCA = immune_subtypes_BRCA.merge(recomp_tumor[["sample_id_short", "PAM50_recomputed", "PAM50Call_RNAseq", "PAM50_final"]], left_on="TCGA Participant Barcode", right_on="sample_id_short", how="left")
immune_subtypes_BRCA.drop(columns=["sampleID_short", "sample_id_short"], inplace=True)
first_cols = immune_subtypes_BRCA.columns[:4]
second_cols = ["pathologic_stage","pathologic_T", "pathologic_N", "pathologic_M", "PAM50_final", "PAM50Call_RNAseq", "PAM50_recomputed"]
other_cols = immune_subtypes_BRCA.columns.difference(first_cols.union(second_cols))
immune_subtypes_BRCA = pd.concat([immune_subtypes_BRCA[first_cols], immune_subtypes_BRCA[second_cols], immune_subtypes_BRCA[other_cols]], axis=1)

In [198]:
immune_subtypes_BRCA.to_csv(r"annotations/BRCA_immune_subtypes_advanced.tsv", index=False, sep="\t")

In [191]:
pathological_cols = [col for col in cl.columns if "pathologic" in col]
pathological_cols

['age_at_initial_pathologic_diagnosis',
 'days_to_initial_pathologic_diagnosis',
 'initial_pathologic_diagnosis_method',
 'pathologic_M',
 'pathologic_N',
 'pathologic_T',
 'pathologic_stage',
 'year_of_initial_pathologic_diagnosis']

In [ ]:
BRCA_clinical = cl[["pathologic_stage","pathologic_t", "pathologic_n", "pathologic_m"]].j

AJCC_Stage_nature2012
Stage IIA     249
Stage IIB     157
Stage IIIA    102
Stage IA       64
Stage I        58
Stage II       40
Stage IIIC     32
Stage IIIB     23
Stage III      18
Stage IV       15
Stage IB       11
Stage X        10
Name: count, dtype: int64

In [72]:
path = r"\\wsl.localhost\Ubuntu\home\stavz\masters\gdc\RNAexp\BRCA_log2_expression"

rna.rename(columns={"sample": "gene_symbol"}, inplace=True)
rna.to_csv(path, index=False, sep="\t")

In [ ]:
["breast_carcinoma_estrogen_receptor_status","er_level_cell_percentage_category", "breast_carcinoma_immunohistochemistry_er_pos_finding_scale", "breast_carcinoma_immunohistochemistry_pos_cell_score", "breast_carcinoma_immunohistochemistry_prgstrn_rcptr_ps_fndng_scl"]
["breast_carcinoma_progesterone_receptor_status", "cytokeratin_immunohistochemistry_staining_method_mcrmtstss_ndctr"]
["gender", "histological_type", "history_of_neoadjuvant_treatment", "icd_o_3_histology", "lymph_node_examined_count", "menopause_status"]
["her2_erbb_pos_finding_cell_percent_category", "lab_proc_her2_neu_immunohistochemistry_receptor_status", "lab_procedure_her2_neu_in_situ_hybrid_outcome_type"]