In [2]:
import os
import pandas as pd
os.chdir("/home/stavz/masters/gdc/APM/")
from pipeline.SV.pipeline import run_sv_pipeline
run_sv_pipeline()

============================================================
SV PIPELINE
============================================================
  VCF directory: /home/stavz/masters/gdc/APM/data/SV/raw_somatic_sv_test
  Output root: /home/stavz/masters/gdc/APM/data/SV/pipeline_output
  Filtering: strict
  Skip VEP: False
  Skip motifs: False

----------------------------------------
STEP 1: Processing VCFs
----------------------------------------
  Running VEP annotation...
    VEP completed: 00b97692-1773-4f7c-b460-a0e6676339bf.somatic_sv.vcf
    VEP completed: 00f4a9e6-aa1c-4132-8df5-814584b98398.somatic_sv.vcf
    VEP completed: 0a2c5763-483b-4aba-ba67-ca63f75037be.somatic_sv.vcf
elements columns: Index(['elem_id', 'type', 'raw_type', 'chrom', 'start', 'end', '0–100kb',
       '100–250kb', '250–500kb', '500–1000kb', 'min_dist_to_any_gene',
       'genes_by_exact_dist'],
      dtype='object')
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/01_vep_vcfs/00b97692-1773-4f7c-b460-a0e6676339bf.somatic_sv.vcf
Samples in VCF: ['NORMAL', 'TUMOR']
Assuming normal sample: NORMAL
Assuming tumor sample: TUMOR
  Filtered to 86 SVs (strict)

/home/stavz/masters/gdc/APM/pipeline/SV/vcf_loader.py:259: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['chrX' 'chr17' 'chr17' 'chr8' 'chr8' 'chr8' 'chr8' 'chr9' 'chr9' 'chr9'
 'chr9' 'chrX' 'chrX' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11'
 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11'
 'chr17_GL000205v2_random' 'chr11' 'chr14' 'chr13' 'chr8' 'chr17' 'chr17'
 'chr17' 'chr17' 'chr8' 'chr18' 'chr18' 'chr18' 'chr18'
 'chr17_GL000205v2_random' 'chr7' 'chr10' 'chr10' 'chr11' 'chr21']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[coords_df.index, ["bnd_remote_chrom", "bnd_remote_pos"]] = coords_df

  Saved: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-B6-A0WV-01A_strict_sv_set.csv
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/01_vep_vcfs/00f4a9e6-aa1c-4132-8df5-814584b98398.somatic_sv.vcf
Samples in VCF: ['NORMAL', 'TUMOR']
Assuming normal sample: NORMAL
Assuming tumor sample: TUMOR
  Filtered to 728 SVs (strict)

/home/stavz/masters/gdc/APM/pipeline/SV/vcf_loader.py:259: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['chr2' 'chr17' 'chr1' 'chr20' 'chr20' 'chr1' 'chr1' 'chr1' 'chr17' 'chr8'
 'chr8' 'chr1' 'chr1' 'chr6' 'chr6' 'chr8' 'chr8' 'chr8' 'chr8' 'chr1'
 'chr8' 'chr1' 'chr8' 'chr3' 'chr8' 'chr1' 'chr1' 'chr1' 'chr8' 'chr8'
 'chr1' 'chr1' 'chr1' 'chr8' 'chr8' 'chr8' 'chr1' 'chr1' 'chr8' 'chr8'
 'chr3' 'chr1' 'chr7' 'chr7' 'chr1' 'chr1' 'chr1' 'chr8' 'chr1' 'chr8'
 'chr8' 'chr8' 'chr8' 'chr8' 'chr19' 'chr5' 'chr8' 'chr8' 'chr8' 'chr8'
 'chr8' 'chr8' 'chr1' 'chr1' 'chr8' 'chr8' 'chr1' 'chr11' 'chr1' 'chr8'
 'chr8' 'chr1' 'chr8' 'chr8' 'chr3' 'chr3' 'chr1' 'chr8' 'chr1' 'chr3'
 'chr3' 'chr1' 'chr12' 'chr12' 'chr6' 'chr6' 'chr6' 'chr6' 'chr6' 'chr6'
 'chr6' 'chr11' 'chr3' 'chr3' 'chr14' 'chr7' 'chr14' 'chr19' 'chr19'
 'chr1' 'chr1' 'chr18' 'chr10' 'chr1' 'chr1' 'chr11' 'chr3' 'chr3' 'chr17'
 'chr20' 'chr2' 'chr2' 'chr5' 'chr12' 'chr12' 'chr2' 'chr2' 'chr7' 'chr21'
 'chr4' 'chr19' 'chr4' 'chr19' 'chr8' 'chr4' 'chr4' 'chr4' 'chr4' 'chr13'
 'chr17' 'chr17' 'chr13' 'chr16' 'chr5' 'chr5' 'chr5' 'chr5' 'chr6' 'chr9'
 'chr1' 'chr5' 'chr5' 'chr6' 'chr5' 'chr5' 'chrUn_KI270538v1' 'chr4'
 'chr4' 'chr3' 'chr4' 'chr4' 'chr6' 'chr6' 'chr6' 'chr12' 'chr16' 'chr2'
 'chr6' 'chr6' 'chr6' 'chr6' 'chr11' 'chr6' 'chr6' 'chr8' 'chr1' 'chr1'
 'chr6' 'chr6' 'chr6' 'chr4' 'chr5' 'chr5' 'chr2' 'chr2' 'chr13' 'chr2'
 'chr2' 'chr2' 'chr2' 'chr11' 'chr5' 'chr10' 'chr3' 'chr7' 'chr1' 'chr7'
 'chr1' 'chr16' 'chr16' 'chr16' 'chr7' 'chr7' 'chr7' 'chr7' 'chr2' 'chr7'
 'chr7' 'chr7' 'chr7' 'chr8' 'chr16' 'chr1' 'chr1' 'chr8' 'chr8' 'chr8'
 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1'
 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr1' 'chr8' 'chr1'
 'chr1' 'chr1' 'chr8' 'chr8' 'chr8' 'chr8' 'chr1' 'chr1' 'chr1' 'chr1'
 'chr1' 'chr1' 'chr1' 'chr1' 'chr8' 'chr8' 'chr11' 'chr6' 'chr7' 'chr1'
 'chr1' 'chr16' 'chr4' 'chr1' 'chr1' 'chr9' 'chr19' 'chrX' 'chr4' 'chrX'
 'chr9' 'chr20' 'chr17' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10'
 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10'
 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10'
 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10'
 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10' 'chr10'
 'chr3' 'chr14' 'chr7' 'chr11' 'chr11' 'chr11' 'chr11' 'chr2' 'chr11'
 'chr11' 'chr3' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr11' 'chr14'
 'chr1' 'chr11' 'chr11' 'chr6' 'chr20' 'chr8' 'chr6' 'chr11' 'chr11'
 'chr14' 'chr18' 'chr15' 'chr12' 'chr3' 'chr3' 'chr12' 'chr2' 'chr12'
 'chr2' 'chr12' 'chr15' 'chr15' 'chr6' 'chr4' 'chr4' 'chr19' 'chr19'
 'chr19' 'chr6' 'chr2' 'chr2' 'chr10' 'chr12' 'chr11' 'chr18' 'chr15'
 'chr15' 'chr12' 'chr12' 'chr15' 'chr15' 'chr12' 'chr8' 'chr7' 'chr7'
 'chr7' 'chr6' 'chrX' 'chr4' 'chr18' 'chr7' 'chr1' 'chr19' 'chr4' 'chr4'
 'chr3' 'chr14_GL000225v1_random' 'chr22' 'chr1' 'chr10' 'chr16' 'chr18'
 'chr18' 'chr12' 'chr19' 'chr3' 'chr14' 'chr18' 'chr17' 'chr3' 'chr3'
 'chr9' 'chr13' 'chr13' 'chr4' 'chr13' 'chr21' 'chr4' 'chr1' 'chr11'
 'chr20' 'chr20' 'chr1' 'chr1' 'chr20' 'chr3' 'chr20' 'chr10' 'chr4'
 'chr19' 'chr17' 'chr9' 'chr16' 'chr9' 'chr17']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[coords_df.index, ["bnd_remote_chrom", "bnd_remote_pos"]] = coords_df

  Saved: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-E9-A244-01A_strict_sv_set.csv
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/01_vep_vcfs/0a2c5763-483b-4aba-ba67-ca63f75037be.somatic_sv.vcf
Samples in VCF: ['NORMAL', 'TUMOR']
Assuming normal sample: NORMAL
Assuming tumor sample: TUMOR
  Filtered to 192 SVs (strict)

/home/stavz/masters/gdc/APM/pipeline/SV/vcf_loader.py:259: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['chr1' 'chr1' 'chr1' 'chr1' 'chr5' 'chr5' 'chr5' 'chr4' 'chr4' 'chr4'
 'chr6' 'chr6' 'chr7' 'chr7' 'chr16' 'chr16' 'chr8' 'chr8' 'chr8' 'chr8'
 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr11' 'chr11' 'chr8' 'chr8' 'chr8'
 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr8' 'chr11'
 'chr8' 'chr9' 'chr9' 'chr9' 'chr9' 'chr9' 'chr9' 'chr9' 'chr9' 'chr10'
 'chr10' 'chr10' 'chr10' 'chr11' 'chr11' 'chr8' 'chr8' 'chr8' 'chr7'
 'chr7' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17'
 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17'
 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17' 'chr17'
 'chrUn_GL000218v1' 'chr20' 'chr20' 'chrX' 'chrX' 'chrX' 'chrX' 'chrX'
 'chrX' 'chrX' 'chrX' 'chr17']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[coords_df.index, ["bnd_remote_chrom", "bnd_remote_pos"]] = coords_df

  Saved: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-A8-A09K-01A_strict_sv_set.csv

----------------------------------------
STEP 2: Motif Scanning
----------------------------------------

[STEP 1] Creating BED intervals...
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-A8-A09K-01A_strict_sv_set.csv
Wrote BED file: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/03_sv_bed/TCGA-A8-A09K-01A_strict_sv_set_flanks_and_overlaps.bed
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-E9-A244-01A_strict_sv_set.csv
Wrote BED file: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/03_sv_bed/TCGA-E9-A244-01A_strict_sv_set_flanks_and_overlaps.bed
Processing: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-B6-A0WV-01A_strict_sv_set.csv
Wrote BED file: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/03_sv_bed/TCGA-B6-A0WV-01A_strict_sv_set_flanks_and_overlaps.bed
  Created 3 BED files

[STEP 2] Extracting FASTA sequences...
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/04_sv_fasta/TCGA-A8-A09K-01A_strict_sv_set_flanks_and_overlaps.fa
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/04_sv_fasta/TCGA-E9-A244-01A_strict_sv_set_flanks_and_overlaps.fa
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/04_sv_fasta/TCGA-B6-A0WV-01A_strict_sv_set_flanks_and_overlaps.fa

[STEP 3] Running FIMO motif scanning...
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/05_fimo_tsv/TCGA-A8-A09K-01A_strict_sv_set_flanks_and_overlaps_fimo.tsv
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/05_fimo_tsv/TCGA-E9-A244-01A_strict_sv_set_flanks_and_overlaps_fimo.tsv
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/05_fimo_tsv/TCGA-B6-A0WV-01A_strict_sv_set_flanks_and_overlaps_fimo.tsv

[STEP 4] Intersecting FIMO hits with SV intervals...
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/06_sv_fimo_merged/TCGA-B6-A0WV-01A_strict_sv_set_flanks_and_overlaps_fimo_merged.bed
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/06_sv_fimo_merged/TCGA-E9-A244-01A_strict_sv_set_flanks_and_overlaps_fimo_merged.bed
  Created: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/06_sv_fimo_merged/TCGA-A8-A09K-01A_strict_sv_set_flanks_and_overlaps_fimo_merged.bed

[STEP 5] Recombining motif hits into SV tables...
[INFO] Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/07_final_sv_with_fimo/TCGA-E9-A244-01A_strict_sv_set.csv
[INFO] Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/07_final_sv_with_fimo/TCGA-A8-A09K-01A_strict_sv_set.csv
[INFO] Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/07_final_sv_with_fimo/TCGA-B6-A0WV-01A_strict_sv_set.csv
\n[STEP 6] Annotating BND neojunction motifs...
[INFO] Reading FIMO TSV: /home/stavz/masters/gdc/APM/data/SV/all_ccre_fimo.tsv
[INFO] 148154 motif hits across 24 chromosomes
[INFO] Assigned 89399 motif-cCRE associations across 59416 cCREs
  TCGA-A8-A09K-01A_strict_sv_set.csv: 96 BNDs...
[INFO] Neojunction motif annotation: 96/96 BNDs annotated, 35244 gained cCRE associations total
  Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-A8-A09K-01A_strict_sv_set.csv
  TCGA-E9-A244-01A_strict_sv_set.csv: 415 BNDs...
[INFO] Neojunction motif annotation: 414/415 BNDs annotated, 170481 gained cCRE associations total
  Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-E9-A244-01A_strict_sv_set.csv
  TCGA-B6-A0WV-01A_strict_sv_set.csv: 48 BNDs...
[INFO] Neojunction motif annotation: 48/48 BNDs annotated, 20926 gained cCRE associations total
  Wrote: /home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-B6-A0WV-01A_strict_sv_set.csv

============================================================
PIPELINE COMPLETE
============================================================
  Processed CSVs: 3
  Final CSVs: 3
  Output directory: /home/stavz/masters/gdc/APM/data/SV/pipeline_output

{'vcf_dir': PosixPath('/home/stavz/masters/gdc/APM/data/SV/raw_somatic_sv_test'),
 'output_root': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output'),
 'processed_csvs': [PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-B6-A0WV-01A_strict_sv_set.csv'),
  PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-E9-A244-01A_strict_sv_set.csv'),
  PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/02_processed_sv_csv/TCGA-A8-A09K-01A_strict_sv_set.csv')],
 'final_csvs': [PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-A8-A09K-01A_strict_sv_set.csv'),
  PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-E9-A244-01A_strict_sv_set.csv'),
  PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched/TCGA-B6-A0WV-01A_strict_sv_set.csv')],
 'motif_dirs': {'bed': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/03_sv_bed'),
  'fasta': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/04_sv_fasta'),
  'fimo_tsv': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/05_fimo_tsv'),
  'fimo_merged': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/06_sv_fimo_merged'),
  'final': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/07_final_sv_with_fimo'),
  'neojunction': PosixPath('/home/stavz/masters/gdc/APM/data/SV/pipeline_output/08_neojunction_enriched')}}

In [2]:
from pipeline.config import PATHS
elements = pd.read_csv(PATHS.ccre_csv)

In [3]:
elements

,chrom,start,end,cCRE_id,ENCODE_id,type
0,chr1,104896,105048,EH38D4327509,EH38E2776520,"CTCF-only,CTCF-bound"
1,chr1,138866,139134,EH38D4327520,EH38E2776521,"pELS,CTCF-bound"
2,chr1,181289,181639,EH38D4327525,EH38E2776524,"DNase-H3K4me3,CTCF-bound"
3,chr1,267925,268171,EH38D4327544,EH38E2776528,"CTCF-only,CTCF-bound"
4,chr1,586036,586264,EH38D4327554,EH38E2776532,"CTCF-only,CTCF-bound"
...,...,...,...,...,...,...
1063873,chrY,21252996,21253278,EH38D6144481,EH38E3951203,dELS
1063874,chrY,21598449,21598656,EH38D6144550,EH38E3951229,"CTCF-only,CTCF-bound"
1063875,chrY,21839503,21839853,EH38D6144588,EH38E3951242,dELS
1063876,chrY,26352857,26353207,EH38D4327371,EH38E3951251,pELS
1063877,chrY,26353315,26353520,EH38D4327372,EH38E3951252,pELS

In [2]:
from pipeline.config import PATHS

In [3]:
ccre = pd.read_csv(PATHS.regulatory_elements_table)

In [4]:
ccre

,elem_id,type,raw_type,chrom,start,end,0–100kb,100–250kb,250–500kb,500–1000kb,min_dist_to_any_gene,genes_by_exact_dist
0,EH38D0432829,dELS,dELS,chr12,67439658,67440000,NaN,NaN,NaN,IFNG,719740,IFNG:719740
1,EH38D0630659,dELS,dELS,chr15,43906148,43906376,NaN,PDIA3,NaN,B2M,159754,"PDIA3:159754,B2M:804877"
2,EH38D0642145,dELS,dELS,chr15,59347433,59347634,NaN,NaN,NaN,ADAM10,597591,ADAM10:597591
3,EH38D0650015,pELS,pELS,chr15,68056149,68056454,PIAS1,NaN,NaN,SMAD3,1848,"PIAS1:1848,SMAD3:992386"
4,EH38D0713843,dELS,dELS,chr16,56801800,56802137,NaN,NLRC5,NaN,NaN,187348,NLRC5:187348
...,...,...,...,...,...,...,...,...,...,...,...,...
49916,EH38D6010649,dELS,dELS,chr9,6467330,6467641,NaN,NaN,NaN,PDCD1LG2,956839,PDCD1LG2:956839
49917,EH38D6010656,dELS,dELS,chr9,6479061,6479217,NaN,NaN,NaN,PDCD1LG2,968570,PDCD1LG2:968570
49918,EH38D6010659,CTCF-only,"CTCF-only,CTCF-bound",chr9,6488401,6488728,NaN,NaN,NaN,PDCD1LG2,977910,PDCD1LG2:977910
49919,EH38D6010663,dELS,dELS,chr9,6502448,6502731,NaN,NaN,NaN,PDCD1LG2,991957,PDCD1LG2:991957
49920,EH38D6010666,dELS,dELS,chr9,6506613,6506961,NaN,NaN,NaN,PDCD1LG2,996122,PDCD1LG2:996122

============================================================
SV PIPELINE
============================================================
  VCF directory: /home/stavz/masters/gdc/APM/data/SV/raw_vcfs
  Output root: /home/stavz/masters/gdc/APM/data/SV/pipeline_output
  Filtering: strict
  Skip VEP: False
  Skip motifs: False

----------------------------------------
STEP 1: Processing VCFs
----------------------------------------
  Running VEP annotation...

----------------------------------------
STEP 2: Motif Scanning
----------------------------------------

[STEP 1] Creating BED intervals...
  Created 0 BED files

[STEP 2] Extracting FASTA sequences...

[STEP 3] Running FIMO motif scanning...

[STEP 4] Intersecting FIMO hits with SV intervals...

[STEP 5] Recombining motif hits into SV tables...

ValueError: all_ccre_fimo_path must be provided or configured in config.PATHS.all_ccre_fimo_tsv

In [2]:
import subprocess

# 1. Check if conda run can find vep
result = subprocess.run(
    ["conda", "run", "--no-banner", "-n", "venp_env", "which", "vep"],
    capture_output=True, text=True
)
print("which vep stdout:", result.stdout)
print("which vep stderr:", result.stderr)
print("returncode:", result.returncode)

# 2. Check if it's maybe mamba instead of conda
result2 = subprocess.run(
    ["which", "conda"],
    capture_output=True, text=True
)
print("\nwhich conda:", result2.stdout)

result3 = subprocess.run(
    ["which", "mamba"],
    capture_output=True, text=True
)
print("which mamba:", result3.stdout)

# 3. Check if the env actually exists
result4 = subprocess.run(
    ["conda", "env", "list"],
    capture_output=True, text=True
)
print("\nconda envs:\n", result4.stdout)

which vep stdout:
which vep stderr: usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: unrecognized arguments: --no-banner

returncode: 2

which conda: /home/stavz/miniforge3/condabin/conda

which mamba: /home/stavz/miniforge3/condabin/mamba


conda envs:

# conda environments:
#
# * -> active
# + -> frozen
                         /home/stavz/miniforge/envs/bio
base                     /home/stavz/miniforge3
vep_env              *   /home/stavz/miniforge3/envs/vep_env

In [3]:
import subprocess
result = subprocess.run(["vep", "--help"], capture_output=True, text=True)
print("returncode:", result.returncode)
print("first 200 chars:", result.stdout[:200])

returncode: 0
first 200 chars: #----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 115.266b84d
  ensembl-compara      : 115.ae48a7a
  en

In [4]:
import subprocess
from pathlib import Path

vcf_dir = Path("/home/stavz/masters/gdc/APM/data/SV/raw_somatic_sv_test")
out_dir = Path("/tmp/vep_test")
out_dir.mkdir(exist_ok=True)

# Grab the first VCF
vcf_file = next(vcf_dir.glob("*.vcf"))
out_vcf = out_dir / vcf_file.name

cmd = [
    "vep",
    "--input_file", str(vcf_file),
    "--output_file", str(out_vcf),
    "--offline", "--cache",
    "--fasta", "/home/stavz/.vep/Homo_sapiens.GRCh38.dna.primary_assembly.fa",
    "--species", "homo_sapiens",
    "--assembly", "GRCh38",
    "--format", "vcf", "--vcf",
    "--force_overwrite", "--everything",
    "--symbol", "--variant_class", "--check_ref",
    "--fork", "4",
]

print("Running:", " ".join(cmd))
result = subprocess.run(cmd, capture_output=True, text=True)
print("returncode:", result.returncode)
print("STDOUT:", result.stdout[-500:] if result.stdout else "(empty)")
print("STDERR:", result.stderr[-500:] if result.stderr else "(empty)")

Running: vep --input_file /home/stavz/masters/gdc/APM/data/SV/raw_somatic_sv_test/00b97692-1773-4f7c-b460-a0e6676339bf.somatic_sv.vcf --output_file /tmp/vep_test/00b97692-1773-4f7c-b460-a0e6676339bf.somatic_sv.vcf --offline --cache --fasta /home/stavz/.vep/Homo_sapiens.GRCh38.dna.primary_assembly.fa --species homo_sapiens --assembly GRCh38 --format vcf --vcf --force_overwrite --everything --symbol --variant_class --check_ref --fork 4
returncode: 0
STDOUT: (empty)
STDERR: 5v1_decoy does not overlap any features
WARNING: line 617 skipped (chrUn_JTFH01001945v1_decoy 44 MantaBND:1075:3:...): Chromosome chrUn_JTFH01001945v1_decoy not found in annotation sources or synonyms; chromosome chrUn_JTFH01001945v1_decoy does not overlap any features
WARNING: line 618 skipped (chrUn_JTFH01001983v1_decoy 248 MantaBND:2:4411...): Chromosome chrUn_JTFH01001983v1_decoy not found in annotation sources or synonyms; chromosome chrUn_JTFH01001983v1_decoy does not overlap any features

In [3]:
cmd = [
    "vep",
    "--input_file", str(vcf_file),
    "--output_file", str(out_vcf),
    "--offline", "--cache",
    "--fasta", "/home/stavz/.vep/Homo_sapiens.GRCh38.dna.primary_assembly.fa",
    "--species", "homo_sapiens",
    "--assembly", "GRCh38",
    "--format", "vcf", "--vcf",
    "--force_overwrite", "--everything",
    "--symbol", "--variant_class", "--check_ref",
    "--fork", "4",
]