In [4]:
from pipeline.config import PATHS
import pandas as pd

mirna_all = pd.read_csv(PATHS.targetscan_predictions, sep="\t")
mirna = pd.read_csv(r'data/miRNA/all_miRNAs_targetscan.csv')

In [8]:
mirna_all[mirna_all["Gene Symbol"] == "ADAM10"]["Transcript ID"].unique()

array(['ENST00000260408.3'], dtype=object)

In [10]:
gtf[(gtf["transcript_id"] == "ENST00000260408.8") & (gtf["feature"] == "UTR")]

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_name,gene_type,transcript_id,transcript_name,transcript_type,tag_list,tag,is_MANE
5596866,chr15,HAVANA,UTR,58749535,58749707,.,-,.,ENSG00000137845.16,ADAM10,protein_coding,ENST00000260408.8,ADAM10-201,protein_coding,"[basic, Ensembl_canonical, GENCODE_Primary, MA...",basic|Ensembl_canonical|GENCODE_Primary|MANE_S...,True
5596867,chr15,HAVANA,UTR,58588809,58597549,.,-,.,ENSG00000137845.16,ADAM10,protein_coding,ENST00000260408.8,ADAM10-201,protein_coding,"[basic, Ensembl_canonical, GENCODE_Primary, MA...",basic|Ensembl_canonical|GENCODE_Primary|MANE_S...,True

In [5]:
mirna[mirna["Gene Symbol"] == "ADAM10"]

,Gene ID,Gene Symbol,miRNA,weighted context++ score,UTR_start,UTR end,num_sites
91424,ENSG00000137845.10,ADAM10,hsa-miR-122-5p,-0.145,[49],[55],1
91425,ENSG00000137845.10,ADAM10,hsa-miR-1251-5p,-0.327,[1522],[1529],1
91426,ENSG00000137845.10,ADAM10,hsa-miR-128-3p,-0.178,[2019],[2025],1
91427,ENSG00000137845.10,ADAM10,hsa-miR-129-5p,-0.064,[2076],[2083],1
91428,ENSG00000137845.10,ADAM10,hsa-miR-140-3p.1,-0.210,[1846],[1852],1
91429,ENSG00000137845.10,ADAM10,hsa-miR-140-3p.2,-0.184,[1847],[1854],1
91430,ENSG00000137845.10,ADAM10,hsa-miR-140-5p,-0.331,[1072],[1079],1
91431,ENSG00000137845.10,ADAM10,hsa-miR-148a-3p,-0.325,[1928],[1935],1
91432,ENSG00000137845.10,ADAM10,hsa-miR-148b-3p,-0.325,[1928],[1935],1
91433,ENSG00000137845.10,ADAM10,hsa-miR-152-3p,-0.317,[1928],[1935],1
91434,ENSG00000137845.10,ADAM10,hsa-miR-153-3p,-0.134,[1273],[1279],1
91435,ENSG00000137845.10,ADAM10,hsa-miR-155-5p,-0.031,[2127],[2133],1
91436,ENSG00000137845.10,ADAM10,hsa-miR-182-5p,-0.141,[428],[434],1
91437,ENSG00000137845.10,ADAM10,hsa-miR-199a-3p,-0.265,[1998],[2004],1
91438,ENSG00000137845.10,ADAM10,hsa-miR-199b-3p,-0.265,[1998],[2004],1
91439,ENSG00000137845.10,ADAM10,hsa-miR-218-5p,-0.069,[1174],[1180],1
91440,ENSG00000137845.10,ADAM10,hsa-miR-219a-5p,-0.040,[1478],[1484],1
91441,ENSG00000137845.10,ADAM10,hsa-miR-224-5p,-0.120,[1571],[1577],1
91442,ENSG00000137845.10,ADAM10,hsa-miR-23a-3p,-0.028,[1492],[1498],1
91443,ENSG00000137845.10,ADAM10,hsa-miR-23b-3p,-0.028,[1492],[1498],1
91444,ENSG00000137845.10,ADAM10,hsa-miR-23c,-0.048,[1492],[1498],1
91445,ENSG00000137845.10,ADAM10,hsa-miR-25-3p,-0.196,"[490, 510]","[496, 516]",2
91446,ENSG00000137845.10,ADAM10,hsa-miR-26a-5p,-0.029,[2118],[2124],1
91447,ENSG00000137845.10,ADAM10,hsa-miR-26b-5p,-0.033,[2118],[2124],1
91448,ENSG00000137845.10,ADAM10,hsa-miR-30a-5p,-0.131,[1472],[1478],1
91449,ENSG00000137845.10,ADAM10,hsa-miR-30b-5p,-0.142,[1472],[1478],1
91450,ENSG00000137845.10,ADAM10,hsa-miR-30c-5p,-0.153,[1472],[1478],1
91451,ENSG00000137845.10,ADAM10,hsa-miR-30d-5p,-0.131,[1472],[1478],1
91452,ENSG00000137845.10,ADAM10,hsa-miR-30e-5p,-0.131,[1472],[1478],1
91453,ENSG00000137845.10,ADAM10,hsa-miR-32-5p,-0.254,"[490, 510]","[496, 516]",2
91454,ENSG00000137845.10,ADAM10,hsa-miR-320a,-0.175,[1588],[1594],1
91455,ENSG00000137845.10,ADAM10,hsa-miR-320b,-0.175,[1588],[1594],1
91456,ENSG00000137845.10,ADAM10,hsa-miR-320c,-0.175,[1588],[1594],1
91457,ENSG00000137845.10,ADAM10,hsa-miR-320d,-0.175,[1588],[1594],1
91458,ENSG00000137845.10,ADAM10,hsa-miR-323a-3p,-0.073,[1836],[1842],1
91459,ENSG00000137845.10,ADAM10,hsa-miR-34a-5p,-0.163,[377],[383],1
91460,ENSG00000137845.10,ADAM10,hsa-miR-34c-5p,-0.200,[377],[383],1
91461,ENSG00000137845.10,ADAM10,hsa-miR-363-3p,-0.211,"[490, 510]","[496, 516]",2
91462,ENSG00000137845.10,ADAM10,hsa-miR-365a-3p,-0.332,[1291],[1298],1
91463,ENSG00000137845.10,ADAM10,hsa-miR-365b-3p,-0.332,[1291],[1298],1
91464,ENSG00000137845.10,ADAM10,hsa-miR-367-3p,-0.222,"[490, 510]","[496, 516]",2
91465,ENSG00000137845.10,ADAM10,hsa-miR-369-3p,-0.178,[530],[537],1
91466,ENSG00000137845.10,ADAM10,hsa-miR-374a-5p,-0.029,[531],[538],1
91467,ENSG00000137845.10,ADAM10,hsa-miR-374b-5p,-0.030,[531],[538],1
91468,ENSG00000137845.10,ADAM10,hsa-miR-409-5p,-0.352,[1069],[1076],1
91469,ENSG00000137845.10,ADAM10,hsa-miR-449a,-0.187,[377],[383],1
91470,ENSG00000137845.10,ADAM10,hsa-miR-449b-5p,-0.212,[377],[383],1
91471,ENSG00000137845.10,ADAM10,hsa-miR-494-3p,-0.044,[520],[526],1
91472,ENSG00000137845.10,ADAM10,hsa-miR-499a-5p,-0.136,[253],[259],1
91473,ENSG00000137845.10,ADAM10,hsa-miR-655-3p,-0.153,"[529, 1254]","[535, 1261]",2
91474,ENSG00000137845.10,ADAM10,hsa-miR-9-5p,-0.083,[53],[59],1
91475,ENSG00000137845.10,ADAM10,hsa-miR-92a-3p,-0.221,"[490, 510]","[496, 516]",2
91476,ENSG00000137845.10,ADAM10,hsa-miR-92b-3p,-0.188,"[490, 510]","[496, 516]",2

In [26]:
from pipeline.config import PRIMARY_GENES
mirna_all[mirna_all["Gene Symbol"].isin(PRIMARY_GENES)].groupby("Gene Symbol")["Transcript ID"].unique()

Gene Symbol
ADAM10      [ENST00000260408.3]
ADAM17      [ENST00000310823.3]
B2M         [ENST00000558401.1]
CALR        [ENST00000316448.5]
CCL5        [ENST00000293272.3]
CD274       [ENST00000381573.4]
CREBBP      [ENST00000262367.5]
CXCL10      [ENST00000306602.1]
CXCL11      [ENST00000306621.3]
CXCL9       [ENST00000264888.5]
EGFR        [ENST00000275493.2]
EP300       [ENST00000263253.7]
IFNG        [ENST00000229135.3]
IFNGR2      [ENST00000290219.6]
IL6         [ENST00000404625.1]
IL6R        [ENST00000344086.4]
IL6ST       [ENST00000381287.4]
IRF1        [ENST00000245414.4]
IRF2        [ENST00000393593.3]
JAK1        [ENST00000342505.4]
JAK2        [ENST00000381652.3]
NFKBIA      [ENST00000216797.5]
NLRC5       [ENST00000436936.1]
PDCD1LG2    [ENST00000397745.2]
PDIA3       [ENST00000300289.5]
PDIA6       [ENST00000272227.3]
PIAS1       [ENST00000249636.6]
PSMB8       [ENST00000395339.3]
PSMB9       [ENST00000395330.1]
PSME1       [ENST00000382708.3]
PSME4       [ENST00000404125.1]
PTPN11      [ENST00000351677.2]
PTPN2       [ENST00000309660.5]
RAET1L      [ENST00000367341.1]
SMAD3       [ENST00000327367.4]
SOCS1       [ENST00000332029.2]
SOCS3       [ENST00000330871.2]
SRC         [ENST00000373578.2]
STAT1       [ENST00000540176.1]
STAT3       [ENST00000585517.1]
TAP1        [ENST00000354258.4]
TAP2        [ENST00000374897.2]
TAPBP       [ENST00000434618.2]
TGFB1       [ENST00000221930.5]
TNFAIP3     [ENST00000237289.4]
Name: Transcript ID, dtype: object

In [27]:
gtf[(gtf["gene_name"] == "STAT1") & (gtf["transcript_id"] == "ENST00000540176.1")]

Empty DataFrame
Columns: [seqname, source, feature, start, end, score, strand, frame, gene_id, gene_name, gene_type, transcript_id, transcript_name, transcript_type, tag_list, tag, is_MANE]
Index: []

In [2]:
from pipeline.genes import get_mirna_targets
from pipeline.config import PATHS
import pandas as pd


genes = pd.read_csv(PATHS.genes_all_features)
gtf = pd.read_parquet(PATHS.gencode_gtf_pq)

df = get_mirna_targets(genes=genes, gtf=gtf, targetscan_path=PATHS.targetscan_predictions, top_n=200, weight_threshold=-0.1)

Loading TargetScan predictions from \home\stavz\masters\gdc\APM\data\miRNA\Predicted_Targets_Context_Scores.default_predictions.txt...
Found 777 TargetScan rows for 66 genes
Found 0 TargetScan rows with transcripts in GTF
Found 0 miRNA-gene pairs meeting threshold

KeyError: 'Transcript ID'

In [ ]:
gtf.rename(columns={"seqname": "chrom"}, inplace=True)

,seqname,source,feature,start,end,score,strand,frame,gene_id,gene_name,gene_type,transcript_id,transcript_name,transcript_type,tag_list,tag,is_MANE
0,chr1,HAVANA,gene,11121,24894,.,+,.,ENSG00000290825.2,DDX11L16,lncRNA,None,None,None,[overlaps_pseudogene],overlaps_pseudogene,False
1,chr1,HAVANA,transcript,11121,14413,.,+,.,ENSG00000290825.2,DDX11L16,lncRNA,ENST00000832824.1,DDX11L16-260,lncRNA,[TAGENE],TAGENE,False
2,chr1,HAVANA,exon,11121,11211,.,+,.,ENSG00000290825.2,DDX11L16,lncRNA,ENST00000832824.1,DDX11L16-260,lncRNA,[TAGENE],TAGENE,False
3,chr1,HAVANA,exon,12010,12227,.,+,.,ENSG00000290825.2,DDX11L16,lncRNA,ENST00000832824.1,DDX11L16-260,lncRNA,[TAGENE],TAGENE,False
4,chr1,HAVANA,exon,12613,12721,.,+,.,ENSG00000290825.2,DDX11L16,lncRNA,ENST00000832824.1,DDX11L16-260,lncRNA,[TAGENE],TAGENE,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7750149,chrM,ENSEMBL,transcript,15888,15953,.,+,.,ENSG00000210195.2,MT-TT,Mt_tRNA,ENST00000387460.2,MT-TT-201,Mt_tRNA,"[basic, Ensembl_canonical, GENCODE_Primary]",basic|Ensembl_canonical|GENCODE_Primary,False
7750150,chrM,ENSEMBL,exon,15888,15953,.,+,.,ENSG00000210195.2,MT-TT,Mt_tRNA,ENST00000387460.2,MT-TT-201,Mt_tRNA,"[basic, Ensembl_canonical, GENCODE_Primary]",basic|Ensembl_canonical|GENCODE_Primary,False
7750151,chrM,ENSEMBL,gene,15956,16023,.,-,.,ENSG00000210196.2,MT-TP,Mt_tRNA,None,None,None,[],,False
7750152,chrM,ENSEMBL,transcript,15956,16023,.,-,.,ENSG00000210196.2,MT-TP,Mt_tRNA,ENST00000387461.2,MT-TP-201,Mt_tRNA,"[basic, Ensembl_canonical, GENCODE_Primary]",basic|Ensembl_canonical|GENCODE_Primary,False
7750153,chrM,ENSEMBL,exon,15956,16023,.,-,.,ENSG00000210196.2,MT-TP,Mt_tRNA,ENST00000387461.2,MT-TP-201,Mt_tRNA,"[basic, Ensembl_canonical, GENCODE_Primary]",basic|Ensembl_canonical|GENCODE_Primary,False